name = "bolt67"
main = "build/server/index.js"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]


[site]
bucket = "./build/client"

[build]
command = "npm run build"

[triggers]
crons = []

[[routes]]
pattern = "bolt.jagadeesh.shop/*"
zone_name = "jagadeesh.shop"
